name: Deploy to GitHub Pages

on:
  push:
    branches: [ "**" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout website branch
        uses: actions/checkout@v4
        with:
          ref: cursor/build-magical-moroccan-travel-platform-caa7

      - name: Use Node if package.json exists
        if: ${{ hashFiles('**/package.json') != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm

      - name: Install dependencies (npm)
        if: ${{ hashFiles('**/package-lock.json') != '' }}
        run: npm ci

      - name: Install dependencies (pnpm)
        if: ${{ hashFiles('**/pnpm-lock.yaml') != '' }}
        run: |
          npm -g i pnpm
          pnpm i --frozen-lockfile

      - name: Install dependencies (yarn)
        if: ${{ hashFiles('**/yarn.lock') != '' }}
        run: |
          npm -g i yarn
          yarn --frozen-lockfile

      - name: Build (best effort)
        if: ${{ hashFiles('**/package.json') != '' }}
        run: |
          set -e
          if [ -f package.json ]; then
            npm run build || echo "No build script; continuing"
          fi

      - name: Build frontend workspace
        env:
          BASE_PATH: /${{ github.event.repository.name }}/
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_WS_URL: ${{ secrets.VITE_WS_URL }}
        run: |
          echo "Using BASE_PATH=$BASE_PATH"
          npm run build -w @hache/frontend
          # SPA fallback for GitHub Pages
          cp apps/frontend/dist/index.html apps/frontend/dist/404.html

      - name: Upload artifact (frontend dist)
        uses: actions/upload-pages-artifact@v3
        with:
          path: apps/frontend/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
